### ISSUE TITLE
Add web app manifest

### ISSUE THREAD

**Issue by JosNun** [jeverhart/nope#7]
Add a web app maniffest to give it an icon when you add it to the homescreen.

Maybe make it a PWA?

**Comment by jeverhart** [comment]
- added a manifest.json & required images
- one of the images exported incorrectly, so i replaced it, but the 'add to home screen' image appears to be off-center still
- originally linked to the manifest in the head, but something changed it from manifest.json to manifest.js...which led to an error, so i'm giving up on that for now

**Comment by JosNun** [comment]
Looks like parcel didn't understand manifest.json and was reading it as a json file (which it should have). I renamed it from `manifest.json` to manifest.webmanifest` and it looks like it runs fine with that (that's how they mention it in their docs).
